blank_issues_enabled: false
contact_links:
  - name: ðŸ“š LangChain Documentation
    url: https://docs.langchain.com/oss/python/integrations/providers/google
    about: View documentation for Google integrations with LangChain
  - name: ðŸ“š API Reference Documentation (langchain-google)
    url: https://reference.langchain.com/python/integrations/langchain_google/
    about: View documentation for Google integrations with LangChain
  - name: ðŸ’¬ LangChain Forum
    url: https://forum.langchain.com/
    about: Ask questions and get help from the community
